import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/other/navbar";
import Footer from "@/components/other/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className=" bg-db text-white"
      style={{
        lineHeight: 1,
      }}
    >
      <body className={`${inter.className}`}>
        <Navbar />
        <div className="max-w-[2560px] w-full mx-auto"> {children}</div>
        <Footer />
      </body>
    </html>
  );
}
